# Generated by Django 4.0.3 on 2022-03-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_posts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='administrator_permissions',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
