# Generated by Django 4.0.3 on 2022-03-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_postcomments_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='comment_date',
        ),
    ]
