# Generated by Django 4.0.3 on 2022-03-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_postcomments_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='comment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
